### ISSUE TITLE
Infrared channel not applied to Meteor-M2 image

### ISSUE THREAD

**Issue by klikis** [dernasherbrezon/r2cloud#108]
Why do I receive meteor with this color?
![a](https://user-images.githubusercontent.com/9518512/105628971-85c30300-5e40-11eb-945b-675a79be314f.jpg)
![Cattura](https://user-images.githubusercontent.com/9518512/105628972-88bdf380-5e40-11eb-85da-4fa9908bdfa5.PNG)

**Comment by Lukas0025** [comment]
Meteor M2 not transmitting R-channel on PID 66. From december (I think) they change active PID from 66 to 68 what is infrared (like NOAA) not Red. It possible to use IR as Red but it is not red. Here is my image with IR as Red channel:
![LRPT_2021_01_24-09_03-rectified](https://user-images.githubusercontent.com/10090137/105629307-89578980-5e42-11eb-988a-c97d6bdd8ecc.png)

and here is without R-channel (I think it looks better):
![LRPT_2021_01_24-09_16-rectified](https://user-images.githubusercontent.com/10090137/105629326-aab87580-5e42-11eb-895a-58bd042804df.png)

i think they change it because meteor M2 is now usually in night time and IR can by use in night too. Here is only IR channel:
![LRPT_2021_01_24-08_58-rectified](https://user-images.githubusercontent.com/10090137/105629400-14d11a80-5e43-11eb-9c4d-730b117b15c3.png)

Active PIDs you can watch here: http://happysat.nl/Meteor/html/Meteor_Status.html
Sorry for clouds. Today is too many clouds in central Europe.
